import io
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from typing import List, Dict, Any, Optional

from graph import graph
from memory.database import get_history, get_report_by_id
from agents.chat_agent import chat_with_report

from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

app = FastAPI(title="ResearchPilot AI Backend API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Adjust for production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# -----------------
# Pydantic Models
# -----------------
class ResearchRequest(BaseModel):
    query: str

class ContinueResearchRequest(BaseModel):
    original_report: str
    deeper_query: str

class ChatRequest(BaseModel):
    report: str
    question: str
    history: List[Dict[str, str]] = []

class PDFRequest(BaseModel):
    report: str
    insights: Dict[str, Any] = {}

# -----------------
# Helpers
# -----------------
def generate_pdf(text: str, insights: Dict[str, Any]) -> io.BytesIO:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer)
    styles = getSampleStyleSheet()
    content = []

    if insights and "confidence_score" in insights:
        content.append(Paragraph("Research Insights", styles["Heading1"]))
        content.append(Paragraph(f"Confidence Score: {int(insights.get('confidence_score', 0) * 100)}%", styles["BodyText"]))
        content.append(Paragraph(f"Source Quality: {int(insights.get('source_quality', 0) * 100)}%", styles["BodyText"]))
        content.append(Paragraph(f"Coverage: {int(insights.get('coverage_score', 0) * 100)}%", styles["BodyText"]))
        
        content.append(Paragraph("Research Gaps", styles["Heading2"]))
        for gap in insights.get("research_gaps", []):
            content.append(Paragraph(f"• {gap}", styles["BodyText"]))
            
        content.append(Paragraph("Contradictions", styles["Heading2"]))
        contradictions = insights.get("contradictions", [])
        if contradictions:
            for item in contradictions:
                content.append(Paragraph(f"• {item}", styles["BodyText"]))
        else:
            content.append(Paragraph("None", styles["BodyText"]))

    content.append(Paragraph("ResearchPilot AI", styles["Title"]))
    content.append(Paragraph("Autonomous Research Report", styles["Heading2"]))
    content.append(Spacer(1, 20))

    for line in text.split("\n"):
        line = line.strip()
        if not line:
            continue
        if line.startswith("# "):
            content.append(Spacer(1, 10))
            content.append(Paragraph(line.replace("# ", ""), styles["Heading1"]))
        elif line.startswith("## "):
            content.append(Paragraph(line.replace("## ", ""), styles["Heading2"]))
        elif line.startswith("### "):
            content.append(Paragraph(line.replace("### ", ""), styles["Heading3"]))
        else:
            content.append(Paragraph(line, styles["BodyText"]))
        
        content.append(Spacer(1, 4))
        
    content.append(Spacer(1, 20))
    content.append(Paragraph("Generated by ResearchPilot AI", styles["Italic"]))

    doc.build(content)
    buffer.seek(0)
    return buffer

# -----------------
# API Endpoints
# -----------------

@app.post("/api/research")
def run_research(req: ResearchRequest):
    try:
        result = graph.invoke({"query": req.query})
        return {
            "formatted_report": result.get("formatted_report", ""),
            "insights": result.get("insights", {}),
            "sources": result.get("sources", []),
            "route": result.get("route", "Unknown")
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/research/continue")
def continue_research(req: ContinueResearchRequest):
    enhanced_query = f"Original Report:\n\n{req.original_report[:3000]}\n\nFurther Research Request:\n\n{req.deeper_query}"
    try:
        result = graph.invoke({"query": enhanced_query})
        return {
            "formatted_report": result.get("formatted_report", ""),
            "insights": result.get("insights", {}),
            "sources": result.get("sources", []),
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/api/history")
def get_research_history():
    history = get_history()
    # history is a list of tuples: (id, query_text, ...) based on ui/app.py logic
    formatted_history = []
    for item in history:
        formatted_history.append({
            "id": item[0],
            "title": item[1]
        })
    return formatted_history

@app.get("/api/report/{report_id}")
def get_report(report_id: int):
    report = get_report_by_id(report_id)
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")
    return {
        "id": report[0],
        "title": report[1],
        "content": report[3]
    }

@app.post("/api/chat")
def handle_chat(req: ChatRequest):
    try:
        answer = chat_with_report(req.report, req.question, req.history)
        return {"answer": answer}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/pdf")
def generate_pdf_endpoint(req: PDFRequest):
    try:
        buffer = generate_pdf(req.report, req.insights)
        return StreamingResponse(
            buffer, 
            media_type="application/pdf",
            headers={"Content-Disposition": "attachment; filename=research_report.pdf"}
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
