from datetime import datetime


def format_report(
    report: str,
    query: str,
    sources: list
):

    timestamp = datetime.now().strftime(
        "%Y-%m-%d %H:%M:%S"
    )

    sources_section = "\n".join(
        [
            f"{idx}. {url}"
            for idx, url in enumerate(
                sources,
                start=1
            )
        ]
    )

    formatted_report = f"""
# Research Report

## Topic

{query}

## Generated On

{timestamp}

---

{report}

---

---

Generated by ResearchPilot AI
"""

    return formatted_report