import sys
import sqlite3

sys.path.append("/Users/somespecies/Desktop/main projects/researchpilot for anti-gra")

from memory.database import DB_NAME, delete_report_by_id, get_history, save_research

def test_sqlite_deletion():
    print("Testing SQLite permanent deletion...")
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    
    # 1. Create a dummy report
    test_query = "Temporary Test Report For Deletion Integration"
    cursor.execute("SELECT id FROM research_history WHERE query = ?", (test_query,))
    existing = cursor.fetchone()
    if existing:
        cursor.execute("DELETE FROM research_history WHERE query = ?", (test_query,))
        conn.commit()
        
    save_research(
        query=test_query,
        route="WEB",
        report="This is a test report body. Generated by ResearchPilot AI",
        sources=[],
        insights={}
    )
    
    # Get its ID
    cursor.execute("SELECT id FROM research_history WHERE query = ?", (test_query,))
    row = cursor.fetchone()
    assert row is not None, "Report was not inserted!"
    report_id = row[0]
    print(f"Report inserted successfully with ID: {report_id}")
    
    # 2. Delete it
    delete_report_by_id(report_id)
    print("Deleted report from database.")
    
    # 3. Verify it is gone
    cursor.execute("SELECT id FROM research_history WHERE id = ?", (report_id,))
    row_after = cursor.fetchone()
    assert row_after is None, "Report still exists in SQLite database after delete_report_by_id!"
    print("Success: SQLite report deletion verified, row is completely deleted.")
    
    conn.close()

if __name__ == "__main__":
    test_sqlite_deletion()
