import sys
from pypdf import PdfReader

def verify_pdf(pdf_path, has_image=True):
    print(f"=== VERIFYING {pdf_path} ===")
    reader = PdfReader(pdf_path)
    
    full_text = ""
    pages_text = []
    for i, page in enumerate(reader.pages):
        text = page.extract_text()
        pages_text.append((i + 1, text))
        full_text += text + "\n"
        
    errors = []
    
    # 1. REMOVE ALL RESEARCHPILOT BRANDING
    for term in ["ResearchPilot AI", "ResearchPilot", "Research Pilot"]:
        if term.lower() in full_text.lower():
            errors.append(f"Legacy branding '{term}' still found in PDF!")
            
    # Platform / Generated by replacement
    if "Poneglyph Research" not in full_text:
        errors.append("Poneglyph Research platform branding not found!")
    if "Poneglyph Intelligence" not in full_text:
        errors.append("Poneglyph Intelligence publisher branding not found!")
        
    # Check for duplicate branding bug
    if "Poneglyph Intelligence Intelligence" in full_text:
        errors.append("Found duplicate branding: 'Poneglyph Intelligence Intelligence'!")
        
    # 2. FIX REFERENCES FORMAT
    import re
    bad_citation = re.findall(r'(?<!\[)\b\d+\]', full_text)
    if bad_citation:
        errors.append(f"Improper reference format (like '1]') found: {bad_citation}")
        
    # 3. REBUILD THE PDF COVER PAGE
    first_page_text = pages_text[0][1]
    if "ACADEMIC ANALYSIS" not in first_page_text:
        errors.append("First page does not contain 'ACADEMIC ANALYSIS' cover header!")
    if "Prepared by" not in first_page_text or "Poneglyph Intelligence" not in first_page_text:
        errors.append("First page metadata 'Prepared by Poneglyph Intelligence' not found!")
    if "Research Domain" not in first_page_text:
        errors.append("First page metadata 'Research Domain' not found!")
    if "Sources Analyzed" not in first_page_text:
        errors.append("First page metadata 'Sources Analyzed' not found!")
    if "Generation Date" not in first_page_text:
        errors.append("First page metadata 'Generation Date' not found!")
        
    # Make sure colons are not present in cover page metadata keys
    if "Research Domain:" in first_page_text or "Sources Analyzed:" in first_page_text or "Generation Date:" in first_page_text:
        errors.append("Found legacy colons in cover page metadata keys!")
        
    # 4. ADD IMAGE CAPTIONS
    if has_image:
        if "Figure 1." not in full_text:
            errors.append("Image caption 'Figure 1.' not found in PDF!")
            
    # Check that legacy headers are not in pages 2+
    for page_num, page_text in pages_text[1:]:
        if "RESEARCH REPORT" in page_text:
            errors.append(f"Found hardcoded 'RESEARCH REPORT' header on Page {page_num}!")
        if "Generated On" in page_text or "Topic" in page_text:
            if page_num != len(pages_text):
                errors.append(f"Found legacy report metadata header on Page {page_num}!")
            
    # Check footer presence on later pages
    for page_num, page_text in pages_text[1:]:
        if "Poneglyph Research" not in page_text or f"Page {page_num}" not in page_text:
            errors.append(f"Expected footer 'Poneglyph Research \u2022 Page {page_num}' not found on Page {page_num}!")
        
    # 5. IMPROVE APPENDIX FORMATTING (only for files with appendix)
    if "appendix" in pdf_path.lower():
        if "Reference URL:" not in full_text:
            errors.append("Evidence Appendix label 'Reference URL:' not found!")
        if "URL:" in full_text:
            cleaned_urls = re.sub(r'Reference\s+URL:', '', full_text)
            if "URL:" in cleaned_urls:
                errors.append("Found legacy 'URL:' label in Appendix!")
                
    # 6. ADD RESEARCH METADATA PAGE
    last_page_text = pages_text[-1][1]
    if "RESEARCH METADATA" not in last_page_text:
        errors.append("Last page does not contain 'RESEARCH METADATA' header!")
    
    meta_keys = [
        "Topic:",
        "Research Domain:",
        "Sources Analyzed:",
        "Unique Sources:",
        "Generated By:",
        "Platform:",
        "Timestamp:"
    ]
    for key in meta_keys:
        if key not in last_page_text:
            errors.append(f"Research Metadata page missing key: '{key}'")
            
    if errors:
        print("Verification FAILED:")
        for err in errors:
            print(f"- {err}")
        return False
    else:
        print("Verification SUCCESS! All audit checks passed.")
        return True

if __name__ == "__main__":
    success = True
    if not verify_pdf("scratch/test_out_new.pdf", has_image=True):
        success = False
    if not verify_pdf("scratch/test_appendix_out_new.pdf", has_image=False):
        success = False
        
    if not success:
        sys.exit(1)
    else:
        print("ALL PDFS VERIFIED SUCCESSFULLY.")
